application: beezwax
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /signup
  script: helloapp.app
  secure: always

- url: /login
  script: helloapp.app
  secure: always

- url: /forgot
  script: helloapp.app
  secure: always

- url: .*
  script: helloapp.app


libraries:
- name: webapp2
  version: "2.5.1"
